---
- name: Install apache web server
  hosts: web
  become: true

  tasks:
    - name: Install httpd with dnf
      ansible.builtin.dnf:
        name: httpd
        state: latest

    - name: Copy index.html to docroot
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 420

    - name: Start and enable httpd service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Open firewall for httpd service
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true
